### ISSUE TITLE
How to generate files in bitstream directory

### ISSUE THREAD

**Issue by jsochacki** [myriadrf/LimeSDR-XTRX_GW#3]
Hello.

I have run through your instructions and have successfully programmed the v5 card with the current images in bitstream folder but now I want to do it with a modified user bitstream so I was hoping you could write a few lines on which .bit files were use when making the bin files int he bitstream directory as there are 3 separate .bit files generated when you run through making the project.  In addition how did you calculate the memory offsets when making the .prm file.  I dont want to get it wrong doing guess and check so was hoping you could just put a few lines in the readme about that particular step please.

**Comment by vbuitvydas** [comment]
Hi, 

note that for rev5  board you have to use LimeSDR-XTRX_fairwaves_rev5 branch. 
You can generate all required programming files by running [gen_prog_file.tcl](https://github.com/myriadrf/LimeSDR-XTRX_GW/blob/LimeSDR-XTRX_fairwaves_rev5/gen_prog_file.tcl) script from vivado tcl console after project compilation.

**Comment by jsochacki** [comment]
Thank you so much for pointing this out.  I'm sorry I didn't notice this on my own.  If you can as well, in order to make an image like "combined_flash_programming_file"  where you program a golden image and then a non golden image how do you determine the memory offsets to use in the n order to add two images to a file like you have in the .prm file?  I know you use the configuration memory file generator in vivado (or tcl script) to do the actual creation of the files but say you have created both the golden image and then the user image, how do you determine the size of those memory offsets as they do not seem to match up end to end in the current files that you have in the repo (i.e. first file ends at 0x001954BF and second one starts at 0x00220000).

**Comment by vbuitvydas** [comment]
You can choose any offset in flash memory, just make sure not to overlap several images. It also depends from FLASH memory organization and on how images are updated. 0x00220000 is next FLASH sector address it allows to fully fit first image and also we can safely update one of the images by deleting FLASH sectors where image resides. You can find more information about MultiBoot feature [here:](https://docs.amd.com/v/u/en-US/xapp1247-multiboot-spi)

Closing this issue, since there is no actual issue.

**Comment by jsochacki** [comment]
Thank you for solving my issue!
